### ISSUE TITLE
引入element-ui后报错

### ISSUE THREAD

**Issue by luodang007** [feinimoshu753/vue-webpack-mutilpage#3]
用的最新的脚手架，lz提供的功能已经可以正常使用。加入elementui后，因为这个里面也有css文件，run dev报错  error  in ./node_modules/_element-ui@2.3.7@element-ui/lib/theme-chalk/index.css,有空的话麻烦帮忙看看如何解决，如果按lz这种打包css分离方式的话。谢谢

Module build failed: Error: "extract-text-webpack-plugin" loader is used without the corresponding plugin, refer to https://github.com/webpack/extract-text-webpack-plugin for the usage example
    at Object.module.exports.pitch (D:\erp\webapp\xampp\htdocs\luodang007\test\node_modules\_extract-text-webpack-plugin@2.1.2@extract-text-webpack-plugin\loader.js:25:9)

最新的package.json
{
  "name": "test",
  "description": "A Vue.js project",
  "version": "1.0.0",
  "author": "luodang007 <363153187@qq.com>",
  "license": "MIT",
  "private": true,
  "scripts": {
    "dev": "node build/dev-server.js",
    "build": "node build/build.js"
  },
  "dependencies": {
    "element-ui": "^2.3.7",
    "style-loader": "^0.21.0",
    "vue": "^2.5.11",
    "vux": "^2.1.1-rc.11"
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 8"
  ],
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.2",
    "babel-preset-env": "^1.6.0",
    "babel-preset-stage-3": "^6.24.1",
    "cross-env": "^5.0.5",
    "css-loader": "^0.28.7",
    "eventsource-polyfill": "^0.9.6",
    "file-loader": "^1.1.4",
    "friendly-errors-webpack-plugin": "^1.1.3",
    "html-webpack-plugin": "^2.28.0",
    "vue-loader": "^13.0.5",
    "vue-template-compiler": "^2.4.4",
    "vux-loader": "^1.0.56",
    "webpack": "^3.6.0",
    "webpack-hot-middleware": "^2.16.1",
    "webpack-merge": "^2.6.1",
    "extract-text-webpack-plugin": "^2.1.2",
    "webpack-dev-server": "^2.9.1"
  },
  "engines": {
    "node": ">= 4.0.0",
    "npm": ">= 3.0.0"
  }
}

index.js引入elementui
import Vue from 'vue'
import ElementUI from 'element-ui';
import 'element-ui/lib/theme-chalk/index.css';
import App from './app'

Vue.use(ElementUI)
/* eslint-disable no-new */
new Vue({
  components: { App }
}).$mount('app')

**Comment by feinimoshu753** [comment]
@luodang007 晚上抽个时间看看，现在脚手架跟新了，项目代码还是老的

**Comment by luodang007** [comment]
@feinimoshu753 多谢，附上我改的最新的脚手架代码
[test2.zip](https://github.com/feinimoshu753/vue-webpack-mutilpage/files/1999193/test2.zip)

**Comment by feinimoshu753** [comment]
@luodang007 我改了一个能跑的版本，应该还有更好的配置，你可以自己研究下。
[vue_demo.zip](https://github.com/feinimoshu753/vue-webpack-mutilpage/files/2001600/vue_demo.zip)

**Comment by luodang007** [comment]
@feinimoshu753 多谢，build下基本可以了，element的样式还有点问题，不过已经跑起来了，我再研究下。
不过dev下会报 webpackJsonp is not defined，我再自己看看吧。谢谢了
